### ISSUE TITLE
Remove vulkan script (v2)

### ISSUE THREAD

**Issue by theofficialgman** [jmcerrejon/PiKISS#210] opened 2024-03-27 15:17 UTC
continuation of https://github.com/jmcerrejon/PiKISS/issues/209

```
Unpacking pi-apps-9fd06f44 (1.0) ...

Reinstalling Vulkan driver...
Vulkan driver reinstalled!.
sh: 1: Syntax error: Unterminated quoted string
E: Problem executing scripts DPkg::Post-Invoke 'fi''
E: Sub-process returned an error code
Apt finished.
```

I am really sick of this... remove these scripts. You clearly cannot be trusted as you continue breaking users installs

**Comment by jmcerrejon** [comment] 2024-03-27 16:21
You have an issue with a bug caused by the old code. By the way, I don't give support to installations through PiApps. So you have two options: Be kind to developers who help you in some tasks (even when bugs appear) and give more information about your issue.

It's weird that according to your GitHub profile, you are not a newbie with Linux and I'm pretty sure you could fix the issue in your OS.

I repeat you, If you don't like my app, don't use it. That's all.

**Comment by theofficialgman** [comment] 2024-03-27 16:51
This isn't an installation of pi-kiss through pi-apps. This is a user error report from your buggy code on an entirely separate app.

**Comment by theofficialgman** [comment] 2024-03-27 16:53
> Be kind to developers who help you in some tasks

Your buggy code is not helpful. I have asked you to remove it.

**Comment by jmcerrejon** [comment] 2024-03-27 16:54
I tried. I’ll close the issue. You are not giving more information. Please, uninstall PiKISS from your OS.

**Closed** 2024-03-27 16:54 UTC
Labels: bug
